### ISSUE TITLE
总感觉卡顿

### ISSUE THREAD

**Issue by Buzzyzz** [stark81/VutronMusic#47]
第一次打开的时候花了比较长的时间，其次在每次打开的时候都会比较慢，然后在页面点击封面或者切歌的时候都会卡一下，希望可以优化

**Comment by stark81** [comment]
什么系统呢？

**Comment by Buzzyzz** [comment]
> 什么系统呢？

mac系统 版本15.1.1

**Comment by stark81** [comment]
可以录个视频看看吗？我这边的intel Mac 15.1系统，程序打开的时间和其他音乐软件差不多，你说的卡顿现象也没有哦。

**Comment by Buzzyzz** [comment]
这个录了视频
 Filmage 2024-12-14_202217.mp4
<https://drive.google.com/file/d/1A-vuZg_QO_JsEZCN5YT35pLBXDQdS_Rd/view?usp=drive_web>

stark81 ***@***.***> 于2024年11月29日周五 17:58写道：

**Comment by stark81** [comment]
挺奇怪的。。是什么处理呢？我自己intel芯片的macos15、windows和ubuntu24都不会出现打开卡这么久的？重装一下看看？

**Comment by Buzzyzz** [comment]
我的是m3芯片  我重装试试

**Comment by stark81** [comment]
> 我的是m3芯片 我重装试试

那应该没用。。我这里打包出来的是intel芯片的版本，你那个安装时系统会转换成m芯片，效率是会变低的，可以自己下载代码，自己打包一下m芯片版本的哦。具体可以参考这里：
[编译环境相关参数 #31](https://github.com/stark81/VutronMusic/issues/31)

**Comment by Buzzyzz** [comment]
重新打包了 比之前快很多，其实我都不会跟着chatgpt一步一步来的    你需要这个包吗？我可以通过邮件发给你

**Comment by stark81** [comment]
> 重新打包了 比之前快很多，其实我都不会跟着chatgpt一步一步来的 你需要这个包吗？我可以通过邮件发给你

谢谢，但暂时不需要哈，因为你打包的版本和我已经上传版本的代码对不上，功能有差异，体验不一致哈。
