### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by lsjg292** [stark81/VutronMusic#59]
作者大大好，看完这个项目感觉很棒想自己学习实现一下，奈何技术水平有限没有方向，不知是否能与你取得联系进而请教，感谢。

**Comment by stark81** [comment]
qq：849966181

**Comment by lsjg292** [comment]
> QQ：849966181
大大你那边有隐私设置，加不了

**Comment by lsjg292** [comment]
1361783272方便的话能否加我
