### ISSUE TITLE
s

### ISSUE THREAD

**Issue by lsjg292** [stark81/VutronMusic#60]
①可能因为大大是MAC系统，windows装的时候也是默认安装位置，没有选项，不知道装到哪儿了。

②UI可能有一些小bug
<img width="1280" alt="7ebc78e33108fa2be0165ce187aec23c" src="https://github.com/user-attachments/assets/b6203fbb-593e-4359-81b2-f1fda5012091" />

③桌面歌词锁住就解不开锁了
<img width="812" alt="91ded19abcfc8b19dc947f664a4d3ff2" src="https://github.com/user-attachments/assets/ff7f05c6-ef8b-46b7-b234-e113ed5f6015" />

④音量按钮延迟很高，音量条有点拖不动，静音切换会卡好几秒。

除此之外都非常好用，界面很好看也很流畅，尤其是苹果的歌词真心喜欢。跟网易云连接的感觉也很完全。

另外，不知道大大有没有兴趣。有一个betterncm（网易云插件）的项目，pc端更新新界面后插件里面的任务栏歌词和
![image](https://github.com/user-attachments/assets/de05e9d0-28d3-4d78-bc47-beb830b10906)
这个界面和歌词插件不能用了，非常类似于苹果歌词，（作者那边提供了降级网易云后可以使用的方法，但经常会卡顿），如果大大有兴趣能参与修复真的很感激。（不用太在意）

太晚了打扰也不好，就在这边发问题。

**Comment by stark81** [comment]
1. windows下的安装目录我明天看一下，好像是默认隐藏起来的，需要在地址栏上直接输入才能进去；
2. 按钮播放状态是小bug，我记录一些。tray图标是刚开始想把mac的状态栏歌词移植过去，但windows和linux都限制了状态栏tray图标的大小，导致显示不出来。可以直接在设置里关闭控制按钮和歌词。已经调整了，但还没打包；
3. 桌面歌词的问题已经修复了，但还没打包；
4. 音量按钮的问题在我这边的三个系统都没有问题。。。
5. 最后一个，windows下的东西完全不懂哈。

现在最新的代码提交里，第2的图标和第3点都是修改好了的，如果有能力可以尝试下载代码自己打包一下哈。不然的话可能要等一等，还有一些功能没写完。

**Comment by stark81** [comment]
新版已发布，修复了上述所提的bug以及运行卡顿的问题。先关闭了，有问题再提。。
