### ISSUE TITLE
对sha512校验值的疑惑

### ISSUE THREAD

**Issue by cheanus** [stark81/VutronMusic#61]
**Describe the bug**
我在制作aur包[AUR (en) - vutronmusic-bin](https://aur.archlinux.org/packages/vutronmusic-bin)时遇到了校验值相关的问题。

对于[VutronMusic.1.1.0_amd64.deb](https://github.com/stark81/VutronMusic/releases/download/v1.1.0/VutronMusic.1.1.0_amd64.deb)文件，[latest-linux.yml](https://github.com/stark81/VutronMusic/releases/download/v1.1.0/latest-linux.yml)文件中的sha512是`swKRZABIIM6sUwieHiwCggw9OWisGS1RWB5bIT9/d+45kGNpU83P2DyHSGL2i2DrTmtCayU1DrYgQ/42s/Yeog==`

但我本地使用sha512sum命令得到的却是`b3029164004820ceac53089e1e2c02820c3d3968ac192d51581e5b213f7f77ee3990636953cdcfd83c874862f68b60eb4e6b426b25350eb62043fe36b3f61ea2`

想请教大佬为什么两个校验码不同呢？

**To Reproduce**
使用sha512sum命令：
```bash
sha512sum VutronMusic.1.1.0_amd64.deb
```

**Expected behavior**
本地与发布的sha512校验值相同

**Device information:**
 - OS Name: archlinux

**Comment by stark81** [comment]
因为有时候mac、windows下的代码没有什么问题，但到了linux下会出现一些特定的bug，比如在linux平台下桌面歌词锁定后无法解锁，所以会微调后再打包，从而导致我上传的linux平台下的校验值和对应tag的校验值不一样的问题。。。

**Comment by cheanus** [comment]
好的，明白了👌
