### ISSUE TITLE
[BUG]启动时间过长

### ISSUE THREAD

**Issue by Young-exec** [stark81/VutronMusic#67]
启动时间过长。
在fedora下运行appimage启动时间过长，使用本地electron运行打开速度正常，如视频所示。
百分百复现。
 OS Name: ### Fedora
 OS Version: 41

https://github.com/user-attachments/assets/5a4fb646-d887-4be2-a5fd-5f6084c7664b

**Comment by stark81** [comment]
我这边很难测试appimage格式，你可以按照下面自己试一下：

注释掉 `buildAssets/builder/config.js`下面的compression: 'maximum', 然后重新打包试试。

**Comment by stark81** [comment]
> 我这边很难测试appimage格式，你可以按照下面自己试一下：
> 
> 注释掉 `buildAssets/builder/config.js`下面的compression: 'maximum', 然后重新打包试试。

我刚试了一下，注释掉再打包启动速度就正常了。。。你可以自己先打包，还有些功能在完善

**Comment by Young-exec** [comment]
> > 我这边很难测试appimage格式，你可以按照下面自己试一下：
> > 注释掉 `buildAssets/builder/config.js`下面的compression: 'maximum', 然后重新打包试试。
> 
> 我刚试了一下，注释掉再打包启动速度就正常了。。。你可以自己先打包，还有些功能在完善

应该是appimage格式问题，无需注释代码，我自己打包成RPM安装后运行正常。

**Comment by stark81** [comment]
> 应该是appimage格式问题，无需注释代码，我自己打包成RPM安装后运行正常。

如果这一行注释掉再打包的话，appimage格式也是正常的。。
